"""Add session_price column

Revision ID: 76deb0b472cb
Revises: 6e5d0295d53d
Create Date: 2025-02-26 14:45:06.035144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76deb0b472cb'
down_revision: Union[str, None] = '6e5d0295d53d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('federated_sessions', sa.Column('session_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('federated_sessions', 'session_price')
    # ### end Alembic commands ###
